### ISSUE TITLE
CKEditor not displayed in Admin portlet

### ISSUE THREAD

**Issue by Cafeinoman** [rotterdam-cs/rcsnewsletter-portlet#4]
Admin portlet do not display the ckeditor, on any tab.
Firebug console return two errors : 

"NetworkError: 404 Not Found - http://domainname.tld/rcsnewsletter-portlet/js/ckeditor/plugins/esvariables/plugin.js?t=D9HJ"

And

"uncaught exception: [CKEDITOR.resourceManager.load] Resource name "esvariables" was not found at "http://domainname.tld/rcsnewsletter-portlet/js/ckeditor/plugins/esvariables/plugin.js?t=D9HJ".

The html code looks like : 

```
<tr>
    <td id="td-ckeditor" colspan="2">
        <input id="inputEditor" type="hidden" name="template">
        <div class="">
            <textarea id="_NewsletterAdmin_WAR_rcsnewsletterportlet_template_editor" class="lfr-editable" contenteditable="true" style="display: none; visibility: hidden;" name="_NewsletterAdmin_WAR_rcsnewsletterportlet_template_editor"></textarea>
        </div>
    </td>
</tr>
```

After a rapid check, there is no esvariables folder. For now, I made direct insert into the database, but not really user-friendly...

**Comment by kasbaoui** [comment]
You are having this issue because Liferay tries to load the default CKEditor which actually has the /esvariables folder.
To fix you only need to copy this folder from {liferay-home}/webapps/ROOT/html/js/editor/ckeditor/plugins/esvariables to the plugins folder of the portlets CKEditor.
