### ISSUE TITLE
Disable catagorization when saving web content? 

### ISSUE THREAD

**Issue by tiggisn** [rotterdam-cs/rcsnewsletter-portlet#6]
Anytime a new content is created the portlet is forcing users to create a category.  Is it possible to disable this?

**Comment by alvartaco** [comment]
Hello,
Is possible that you explain the issue you are facing with a kind of step by step, and maybe I can give you an option, or maybe try to reproduce it.

Thank you
Alejandro

**Comment by tiggisn** [comment]
After installing the portlet
1. Create or edit a new web content or edit an existing web content in any site
2. Create publish
3. Error “Your request failed to complete”
4. User are forced to choose a category “ rss-news, press-release, events, newsletter, or rss general. 

How do I disable this option? 

If the user or admin wants to tag a web content for the newsletter then it should be by individuals article not every single time.

**Comment by alvartaco** [comment]
I think that you need to remove them from the portal-ext.properties.
Did you write them there?

**Comment by tiggisn** [comment]
No I did not write anything in the portal-ext.properteis.  This behavior is on by default. 

What should I write in properties file to disable this behavior?

**Comment by alvartaco** [comment]
In the plugin's document you can read:

Setting up the portal to use RCS Newsletter-portlet
In order to use RCS Newsletter-portlet, the following configuration is suggested to be set in portal-ext.properties file1
journal.article.types=rcs-news,rcs-press-release,rcs-events,rcs-newsletter,rcs-general

But it seems that the error you are facing is not related to the portlet, please try this, if you can of course, install a clean Liferay, start it and create a new web content, it sounds to me that you are facing a LR issue, not a plugin's one.

Which Version of LR are you using.?

**Comment by tiggisn** [comment]
Ok,

I see the problem, we have configured the portal according to the plugin documentation.  This is forcing all journal article to be categorized prior to being saved. 

My question is that if we don’t want every web content to have the following "rcs-news,rcs-press-release,rcs-events,rcs-newsletter,rss-general” categorization;  Should we remove "journal.article.types=rcs-news,rcs-press-release,rcs-events,rcs-newsletter,rss-general” and only manually categorize content that we wish to be part of the newsletter content? 

If so we should we use only  "rcs-news,rcs-press-release,rcs-events,rcs-newsletter,rss-general” or any other tags that we create?

**Comment by alvartaco** [comment]
Well, yes, you can remove them and use one of the other available options to categorize web contents:

In Categorization section choose at least one of the following methods.

Type: choose rcs-newsletter, if it wass added to portal-ext.properties.

Categories: You'll need to create a category in Liferay / Site Administration / Content / Categories, name it newsletter.

Tags: Just type newsletter.

HTH
Alejandro

**Comment by tiggisn** [comment]
Alejandro -  

Would it be possible to get you guys to update this for Liferay 7?

**Comment by tiggisn** [comment]
Would it be possible to get this in LR 7?

On Mon, Oct 26, 2015 at 2:38 PM, Shahab Noori <shahab.noori@knowledgeinc.com
> wrote:

> After installing the portlet
>
> 1. Create or edit a new web content or edit an existing web content in any
> site
> 2. Create publish
> 3. Error “Your request failed to complete”
> 4. User are forced to choose a category “ rss-news, press-release, events,
> newsletter, or rss general.
>
> How do I disable this option?
>
> If the user or admin wants to tag a web content for the newsletter then it
> should be by individuals article not every single time.
>
>
>
>
>
>
> On Oct 26, 2015, at 2:33 PM, Alejandro E. Alvarez <
