### ISSUE TITLE
Localization not accepting Greek characters

### ISSUE THREAD

**Issue by kyripapa** [rotterdam-cs/rcsnewsletter-portlet#7]
In WEB-INF/classes I have inserted the files  Language_el_GR.properties & Newsletter_el_GR.properties with the appropriate translation with Greek characters and it shows broken characters instead. Furthermore, I have tried changing the characters with native to ACII tool but instead showing Greek, it shows ??. Is there any workaround for the issue?
Thank you in advance,
Korina Papadopoulou

**Comment by alvartaco** [comment]
Hello

The place to add your properties files is not classes in the compiled war.

You need to add them in 

https://github.com/rotterdam-cs/rcsnewsletter-portlet/tree/lr621%2Blr6210%2B_multisite/docroot/WEB-INF/src

and then recompile to generate the war.

Let me know if this fix your problem.

KR
Alejandro.

**Comment by kyripapa** [comment]
Sorry for the delayed answer this fixed my problem thank you!
